# Usage
#   Start:                      docker compose -f docker-compose.yml -f supabase/docker-compose.yml up -d
#         -> Reset database:    sudo rm -rf supabase/volumes/db/data
#   Stop:                       docker compose -f docker-compose.yml -f supabase/docker-compose.yml down -d

name: Coffee_Shop_Manager

services:
  frontend:
    container_name: react-frontend
    image: node:20
    # build:
      # context: ./koffieblik
    ports:
      - "3000:3000"
    volumes:
      - ./koffieblik:/app
      - ./koffieblik/node_modules:/app/node_modules
    working_dir: /app
    env_file:
      - ./.env
    depends_on:
      - db
    command: npm run dev

# volumes:
  # node_modules:
