# Usage
# Please ensure a .env file copied from .env.example exists in root

# PROFILES:
# DEV - Runs everything locally including supabase [.env]
# PROD - Runs frontend and API locally and references hosted supabase [.env.prod]

# START:
#   DEV:
#     ENV_FILE=.env docker compose --profile dev up
#   PROD:
#     ENV_FILE=.env.prod docker compose --profile prod up

# STOP:
#   DEV:
#     ENV_FILE=.env docker compose --profile dev down
#   PROD:
#     ENV_FILE=.env.prod docker compose --profile prod sown

# reset:    Reset database [this will initialize it with the values from data.sql again]
  # stop the docker
  # rm -rf supabase/volumes/db/data
  # start the docker

name: Coffee_Shop_Manager

services:
  frontend:
    container_name: react-frontend
    image: node:20
    ports:
      - "3000:3000"
    volumes:
      - ./koffieblik:/app
      - ./koffieblik/node_modules:/app/node_modules
    working_dir: /app
    env_file:
      - ${ENV_FILE}
    # depends_on:
    #   - db
    command: npm run dev
    profiles: ["dev", "prod"]

  api:
    container_name: ts-api
    image: node:20
    working_dir: /app
    volumes:
      - ./API:/app
      - ./API/node_modules:/app/node_modules
    ports:
      - "${API_PORT}:5000"
    command: npx ts-node src/server.ts
    env_file:
      - ${ENV_FILE}
    # depends_on:
    #   - db
    profiles: ["dev", "prod"]
