# Usage
# Please ensure a .env file copied from .env.example exists in root
# start:
#         docker compose up

# stop:
#         docker compose down

# reset:    Reset database [this will initialize it with the values from data.sql again]
  # stop the docker
  # rm -rf supabase/volumes/db/data
  # start the docker

name: Coffee_Shop_Manager

services:
  frontend:
    container_name: react-frontend
    image: node:20
    # build:
      # context: ./koffieblik
    ports:
      - "3000:3000"
    volumes:
      - ./koffieblik:/app
      - ./koffieblik/node_modules:/app/node_modules
    working_dir: /app
    env_file:
      - ./.env
    depends_on:
      - db
    command: npm run dev

  api:
    container_name: ts-api
    image: node:20
    working_dir: /app
    volumes:
      - ./API:/app
      - ./API/node_modules:/app/node_modules
    ports:
      - "${API_PORT}:5000"
    command: npx ts-node src/server.ts
    env_file:
      - ./.env
    depends_on:
      - db

# volumes:
  # node_modules:
