# version: "3.8"

services:
# DATABASE
  db:
    build: ./db
    container_name: coffee_shop_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffee_shop_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps/koffieblik.sql:/docker-entrypoint-initdb.d/koffieblik.sql

  # FRONTEND
  frontend:
    build:
      context: ./koffieblik
    ports:
      - "3000:3000"
    volumes:
      - ./koffieblik:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=coffee_shop_db
    depends_on:
      - db
    command: npm run dev