name: CI for Koffieblik

on:
  push:
    branches: [main]
    paths:
      - 'koffieblik/**'
      - '.github/workflows/koffieblik_ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    defaults:
      run:
        working-directory: ./koffieblik

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd ./API && npm ci --legacy-peer-deps
          cd ../koffieblik && npm ci --legacy-peer-deps

      - name: Copy PROD .env from secret
        run: echo "${{ secrets.ENV_PROD }}" > .env.prod

      - name: Start Docker Compose (PROD)
        run: |
          ENV_FILE=.env.prod docker compose --profile prod up -d
          echo "Waiting for API to start..."
          for i in {1..20}; do
            if curl -s http://localhost:5000/health; then
              echo "API is ready!"
              break
            fi
            sleep 3
          done

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests with Newman
        run: |
          newman run API/tests/Testing.postman_collection.json --global-var "URL=http://localhost:5000/" --verbose

      - name: Run Playwright Tests via Makefile
        run: make test

      - name: Stop Docker Compose
        if: always()
        run: ENV_FILE=.env.prod docker compose --profile prod down
