name: CI for Koffieblik

on:
  push:
    branches: [main]
    paths:
      - 'koffieblik/**'
      - '.github/workflows/koffieblik_ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./koffieblik

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build the app
        run: npm run build
